services:
  backend:
    build:
      context: .
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=stackoverflow_db
      - DB_HOST=db
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - db
      - elasticsearch
    command: npm run start:feed

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stackoverflow_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  pg_data:
  es_data:
